plugin:
    has_options: false

    tools:
        - name: formalibre_invoice
          is_displayable_in_workspace: false
          is_displayable_in_desktop: true
          class: dollar
        - name: formalibre_my_shared_workspaces_tool
          is_displayable_in_workspace: false
          is_displayable_in_desktop: true
          class: book
        - name: formalibre_my_orders
          is_displayable_in_workspace: false
          is_displayable_in_desktop: true
          class: book

    widgets:
        - name: formalibre_campus
          is_configurable: false

    admin_tools:
        - name: formalibre_admin_invoice
          class: dollar

        - name: formalibre_product_creator
          class: cart-plus

        - name: formalibre_shared_workspaces_admin_tool
          class: book
