services:
    formalibre.var_extension:
        arguments:
            - "@service_container"
        class: FormaLibre\InvoiceBundle\Form\Extension\VatExtension
        tags:
            - { name: form.type_extension, alias: form }
