parameters:
    #generate it with scrypt, bcrypt or PBKDF2
    formalibre_encryption_secret: bcb04b7e103a0cd8b54763051cef08bc55abe029fdebae5e1d417e2ffb2a00a3 #you obv need to change it
    formalibre_target_platform_url: "localhost/nico/Claroline/web/app_dev.php"
    formalibre_encrypt: false

services:
    formalibre.var_extension:
        arguments:
            - "@service_container"
        class: FormaLibre\InvoiceBundle\Form\Extension\VatExtension
        tags:
            - { name: form.type_extension, alias: form }
