workspace_shared_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/SharedWorkspaceController.php"
    type: annotation
    prefix: /workspace

invoice_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/InvoiceController.php"
    type: annotation
    prefix: /

admin_invoice_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/AdministrationController.php"
    type: annotation
    prefix: /

chart_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/ChartController.php"
    type: annotation
    prefix: /
