workspace_shared_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/SharedWorkspaceController.php"
    type: annotation
    prefix: /shared/

invoice_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/InvoiceController.php"
    type: annotation
    prefix: /

admin_invoice_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/AdministrationController.php"
    type: annotation
    prefix: /admin

chart_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/ChartController.php"
    type: annotation
    prefix: /chart

product_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/ProductController.php"
    type: annotation
    prefix: /product

support_credit_controller:
    resource: "@FormaLibreInvoiceBundle/Controller/SupportCreditController.php"
    type: annotation
    prefix: /credit/
