#this file should be removed if I manage to remove the suggestConfiguration method from FormaLibreInvoiceBundle
jms_payment_paypal:
    username: blablabla
    password: blablabla
    signature: blablabla
    debug: true
